### ISSUE TITLE
Fornite can't be downloaded

### ISSUE THREAD

**Issue by Hamsterman** [tpill90/epic-lancache-prefill#46] opened 2023-11-12 16:41 UTC
I added Fornite and get this error:

[4:37:22 PM] Starting Fortnite
[4:37:23 PM] Unexpected download error : Index was outside the bounds of the array.  Skipping app...

Other apps work fine.

I worked after I a
./EpicPrefill clear-cache

**Comment by tpill90** [comment] 2024-05-03 17:10
Have you seen this issue again recently @Hamsterman ?  I tried Fortnite myself just now and I get no such error.

I'm going to close this since it looks like its working, but if the issue is still reproducible for you please feel free to reopen this issue.

**Closed as completed by tpill90** 2024-05-03 17:10 UTC
